name: Fetch

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 19 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"
      - uses: actions/checkout@v2
      - uses: yjl9903/fetch-captain@v0
        with:
          roomid: '22918711'
          ruid: '646432928'
          sender: ${{ secrets.SENDER }}
          sender_pass: ${{ secrets.SENDER_PASS }}
          sender_host: ${{ secrets.SENDER_HOST }}
          receiver: ${{ secrets.RECEIVER }}
      - name: Push
        run: |
          mv *.csv ./data/
          git add *.csv
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "Update"
          git push

